2021-08-26 03:23:10,109 INFO    MainThread:28396 [wandb_setup.py:_flush():69] setting env: {}
2021-08-26 03:23:10,109 INFO    MainThread:28396 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-26 03:23:10,109 INFO    MainThread:28396 [wandb_init.py:_log_setup():342] Logging user logs to /home/vicc/neural-sculpture/wandb/run-20210826_032310-1hf9fn07/logs/debug.log
2021-08-26 03:23:10,110 INFO    MainThread:28396 [wandb_init.py:_log_setup():343] Logging internal logs to /home/vicc/neural-sculpture/wandb/run-20210826_032310-1hf9fn07/logs/debug-internal.log
2021-08-26 03:23:10,111 INFO    MainThread:28396 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4318f34d10>
2021-08-26 03:23:10,111 INFO    MainThread:28396 [wandb_init.py:init():375] calling init triggers
2021-08-26 03:23:10,111 INFO    MainThread:28396 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'batch_size': 4, 'init_tolerance': -1, 'iters_per_res': 8, 'max_iters_per_cam': 32, 'camera': namespace(init_num_cameras=8, mapping_span=6.283185307179586, mapping_type='sdfdiff', max_num_cameras=8, shuffle_order=False), 'loss': namespace(image_loss_weight=0.0002, lp_loss_weight=0.001, sdf_loss_weight=0.001)}
2021-08-26 03:23:10,111 INFO    MainThread:28396 [wandb_init.py:init():397] re-initializing run, found existing run on stack: bsiw5uz5
2021-08-26 03:23:10,113 INFO    MainThread:28396 [wandb_run.py:finish():1254] finishing run viccpoes/neural-sculpture/bsiw5uz5
2021-08-26 03:23:10,113 INFO    MainThread:28396 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-26 03:23:10,113 INFO    MainThread:28396 [wandb_run.py:_restore():1526] restore
2021-08-26 03:23:10,428 INFO    MainThread:28396 [wandb_run.py:_restore():1526] restore
2021-08-26 03:23:10,438 ERROR   MainThread:28396 [wandb_init.py:init():801] error
Traceback (most recent call last):
  File "/opt/conda/envs/neural-sculpture/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1562, in _atexit_cleanup
    self._on_finish()
  File "/opt/conda/envs/neural-sculpture/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1719, in _on_finish
    self._backend.interface.publish_telemetry(self._telemetry_obj)
  File "/opt/conda/envs/neural-sculpture/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 228, in publish_telemetry
    self._publish(rec)
  File "/opt/conda/envs/neural-sculpture/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 530, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/neural-sculpture/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 775, in init
    run = wi.init()
  File "/opt/conda/envs/neural-sculpture/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 412, in init
    self._wl._global_run_stack[-1].finish()
  File "/opt/conda/envs/neural-sculpture/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1258, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/opt/conda/envs/neural-sculpture/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1571, in _atexit_cleanup
    self._backend.cleanup()
  File "/opt/conda/envs/neural-sculpture/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 167, in cleanup
    self.interface.join()
  File "/opt/conda/envs/neural-sculpture/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 830, in join
    _ = self._communicate(record)
  File "/opt/conda/envs/neural-sculpture/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/envs/neural-sculpture/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
